fruits = ['papaya','mandarina','platano','otra frutilla']
print("=================================")
print("==========Lista tal cual=========")
print("=================================")
print(fruits)
fruits.sort()
print("=================================")
print("=====Lista Ordenada Ascendente===")
print("=================================")
print(fruits)
fruits.sort(reverse=True)
print("=================================")
print("===Lista Ordenada Descendente====")
print("=================================")
print(fruits)
print("=================================")